export const DECREMENT = 'DECREMENT'
export const INCREASE_WORK_TIMER = 'INCREASE_WORK_TIMER'
export const DECREASE_WORK_TIMER = 'DECREASE_WORK_TIMER'
export const INCREASE_BREAK_TIMER = 'INCREASE_BREAK_TIMER'
export const DECREASE_BREAK_TIMER = 'DECREASE_BREAK_TIMER'
export const ADD_WORK_TIME = 'ADD_WORK_TIME'
export const SUBTRACT_WORK_TIME = 'SUBTRACT_WORK_TIME'
export const ADD_BREAK_TIME = 'ADD_BREAK_TIME'
export const SUBTRACT_BREAK_TIME = 'SUBTRACT_BREAK_TIME'
export const RESET = 'RESET'
//for todos
export const HANDLE_INPUT = "HANDLE_INPUT"
export const ADD_TASK = "ADD_TASK"
export const DELETE_TASK = "DELETE_TASK"
export const LETS_EDIT = "LETS_EDIT"
export const HANDLE_EDIT = "HANDLE_EDIT"
export const OPEN_MODAL = "OPEN_MODAL"
export const CLOSE_MODAL = "CLOSE_MODAL"
